// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Surrealdb_Query from "../src/query/Surrealdb_Query.mjs";
import * as Surrealdb_Value from "../src/value/Surrealdb_Value.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Surrealdb_Surreal from "../src/connection/Surrealdb_Surreal.mjs";

async function run() {
  let db = Surrealdb_Surreal.make();
  await Surrealdb_Surreal.connect(db, "ws://127.0.0.1:8787/rpc", "test", "rescript_surrealdb", Primitive_option.some(Surrealdb_Surreal.staticAuthentication(Surrealdb_Surreal.rootConnectAuth("root", "root", undefined))), false, undefined, undefined, undefined);
  let values = await Surrealdb_Query.resolve(Surrealdb_Query.text(db, "RETURN 1; RETURN 2;", undefined, undefined));
  await Surrealdb_Surreal.close(db);
  return values.map(Surrealdb_Value.toText);
}

export {
  run,
}
/* Surrealdb_Query Not a pure module */
