// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Surrealdb_Live from "../src/live/Surrealdb_Live.mjs";
import * as Surrealdb_Uuid from "../src/value/Surrealdb_Uuid.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Surrealdb_Surreal from "../src/connection/Surrealdb_Surreal.mjs";
import * as Surrealdb_LiveSubscription from "../src/live/Surrealdb_LiveSubscription.mjs";

async function subscribe() {
  let db = Surrealdb_Surreal.make();
  await Surrealdb_Surreal.connect(db, "ws://127.0.0.1:8787/rpc", "test", "rescript_surrealdb", Primitive_option.some(Surrealdb_Surreal.staticAuthentication(Surrealdb_Surreal.rootConnectAuth("root", "root", undefined))), false, undefined, undefined, undefined);
  let subscription = await Surrealdb_Live.awaitManaged(Surrealdb_Live.tableNamedOn(Surrealdb_Surreal.asQueryable(db), "widgets"));
  let queryId = Surrealdb_Uuid.toString(Surrealdb_LiveSubscription.id(subscription));
  await Surrealdb_LiveSubscription.kill(subscription);
  await Surrealdb_Surreal.close(db);
  return queryId;
}

export {
  subscribe,
}
/* Surrealdb_Live Not a pure module */
