// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Surrealdb_Surreal from "../src/connection/Surrealdb_Surreal.mjs";

async function make() {
  let db = Surrealdb_Surreal.make();
  await Surrealdb_Surreal.connect(db, "ws://127.0.0.1:8787/rpc", "test", "rescript_surrealdb", Primitive_option.some(Surrealdb_Surreal.staticAuthentication(Surrealdb_Surreal.rootConnectAuth("root", "root", undefined))), false, undefined, undefined, undefined);
  let status = Surrealdb_Surreal.status(db);
  let connected = Surrealdb_Surreal.isConnected(db);
  await Surrealdb_Surreal.close(db);
  return [
    status,
    connected
  ];
}

export {
  make,
}
/* Surrealdb_Surreal Not a pure module */
